### ISSUE TITLE
AppendToStream - can it return the underlying StoredProcedureResponse?

### ISSUE THREAD

**Issue by ElasticCoder** [ASOS/SimpleEventStore#5]
It would be useful if AppendToStream returns the underlying StoredProcedureResponse. This will allow clients to extract the RU cost if they desire it.

**Comment by asosMikeGore** [comment]
If we do this via AppendToStream we potentially end up with a leaky abstraction e.g these settings aren't relevant to the in-memory engine.  Thinking it makes sense to do this via separate config calls that are particular to the persistence engine.  What do you think?

**Comment by asosMikeGore** [comment]
@ElasticCoder I've just pushed a change onto the configEnhancements branch that should give you what you need.  At present this only works for successful calls - if you need data for DocumentClientExceptions then let me know.

Rather than returning the whole StoredProcedureResponse I have returned a subset of the information.  The main reason for this is to ensure you don't end up tightly coupled to the underlying operation being used against Cosmos DB - for example if we used a different call in the future this would be a breaking change.

The README.md file on the branch has been updated to show an example of how to get hold of the data.

**Comment by asosMikeGore** [comment]
The change has now been merged into master.  If we want more data like this let's deal with it via a separate issue.
